global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
  
  - job_name: elasticsearch
    static_configs:
      - targets: ["elasticsearch:9200"]
  
  - job_name: jaeger-collector
    static_configs:
      - targets: ["jaeger-collector:14269"]
  
  - job_name: jaeger-query
    static_configs:
      - targets: ["jaeger-query:16687"]

  - job_name: basic-app
    static_configs:
      - targets: ["host.local:8000"]
