apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    version: 1
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    overwrite: true

  - name: Jaeger
    type: jaeger
    version: 1
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    overwrite: true
